web:
    build: .
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ../htdocs:/var/www/html
    links:
        - mysql
    env_file:
        - env
mysql:
    image: mysql:5.6.23
    ports:
        - "3306:3306"
    env_file:
        - env
    volumes_from:
        - dbdata

dbdata:
    image: tianon/true
    volumes:
        - /var/lib/mysql
